### PR TITLE
Fix the issue with missing first/last name attribute on Users load

### PR DESCRIPTION
**Pull request by mikecherk**
Some users in my organization were missing First name and it caused the plugin to fail. Made a simple fix. Please check and if you feel ok with it, merge into master. Thanks!

### CODE REVIEW

**Comment by carfup** [comment]
Hey,
Thanks mike for this one.
It will be integrated into the next release which will come soon normally !

**Comment by mikecherk** [comment]
Hi, thanks for your answer! By the way, after I got all users loaded, I noticed that filtering of users also causes an issue with first/last name. It is just a couple of lines above my initial fix. I can create another pull request if you need, just don't want to bother you too much with minor staff =)

**Comment by carfup** [comment]
Yeah all is fixed in my dev branch.
I keep you updated while it's published !

Thanks a lot Mike.

**Comment by carfup** [comment]
Hello Mike,

The fix is included in the next release (you can find the pre-release here : https://github.com/carfup/XTBPlugins.PersonalViewsMigration/releases/tag/1.2019.6.8-beta) and will be published later this week.

Clément

**Comment by carfup** [comment]
Hi Mike,

#21 : latest version was publish fixing that issue !
Thanks for the feedback here

**Pull request closed without merging**
